export {default as Home} from './Home/Home'
export {default as Profile} from './Profile/Profile'
export {default as SignUpPage} from './SignUpPage/SignUpPage'
export {default as StepOnePage} from './StepOnePage/StepOnePage'
export {default as StepTwoPage} from './StepTwoPage/StepTwoPage'