export {default as Home} from './Home/Home'
export {default as SignUpPage} from './SignUpPage/SignUpPage'
export {default as StepOnePage} from './StepOnePage/StepOnePage'
export {default as StepTwoPage} from './StepTwoPage/StepTwoPage'
export {default as StepThreePage} from './StepThreePage/StepThreePage'
export {default as StepSixPage} from './StepSixPage/StepSixPage'
export {default as LoginPage} from './LoginPage/LoginPage'